[2025-02-12T22:18:45.738+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-12T22:18:45.765+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: zip_csv_ingestion.extract_csv scheduled__2025-02-11T00:00:00+00:00 [queued]>
[2025-02-12T22:18:45.777+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: zip_csv_ingestion.extract_csv scheduled__2025-02-11T00:00:00+00:00 [queued]>
[2025-02-12T22:18:45.777+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-02-12T22:18:45.797+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): extract_csv> on 2025-02-11 00:00:00+00:00
[2025-02-12T22:18:45.809+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=103) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-12T22:18:45.810+0000] {standard_task_runner.py:72} INFO - Started process 106 to run task
[2025-02-12T22:18:45.814+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'zip_csv_ingestion', 'extract_csv', 'scheduled__2025-02-11T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/csv_to_gcs.py', '--cfg-path', '/tmp/tmpwrm4bf_i']
[2025-02-12T22:18:45.815+0000] {standard_task_runner.py:105} INFO - Job 11: Subtask extract_csv
[2025-02-12T22:18:45.899+0000] {task_command.py:467} INFO - Running <TaskInstance: zip_csv_ingestion.extract_csv scheduled__2025-02-11T00:00:00+00:00 [running]> on host d402094725ac
[2025-02-12T22:18:46.013+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='zip_csv_ingestion' AIRFLOW_CTX_TASK_ID='extract_csv' AIRFLOW_CTX_EXECUTION_DATE='2025-02-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-11T00:00:00+00:00'
[2025-02-12T22:18:46.014+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-12T22:18:46.014+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-12T22:18:46.015+0000] {logging_mixin.py:190} INFO - Current task name:extract_csv state:running start_date:2025-02-12 22:18:45.765782+00:00
[2025-02-12T22:18:46.015+0000] {logging_mixin.py:190} INFO - Dag name:zip_csv_ingestion and current dag run status:running
[2025-02-12T22:18:46.016+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-12T22:18:46.017+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/csv_to_gcs.py", line 25, in extract_csv
    with zipfile.ZipFile(LOCAL_ZIP_PATH, "r") as zip_ref:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/zipfile/__init__.py", line 1354, in __init__
    self._RealGetContents()
  File "/usr/local/lib/python3.12/zipfile/__init__.py", line 1421, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
[2025-02-12T22:18:46.048+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-02-12T22:18:46.049+0000] {logging_mixin.py:190} INFO - Task start:2025-02-12 22:18:45.765782+00:00 end:2025-02-12 22:18:46.047688+00:00 duration:0.281906
[2025-02-12T22:18:46.050+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): extract_csv> dag:<DAG: zip_csv_ingestion> dagrun:<DagRun zip_csv_ingestion @ 2025-02-11 00:00:00+00:00: scheduled__2025-02-11T00:00:00+00:00, state:running, queued_at: 2025-02-12 22:18:23.705319+00:00. externally triggered: False>
[2025-02-12T22:18:46.050+0000] {logging_mixin.py:190} INFO - Failure caused by File is not a zip file
[2025-02-12T22:18:46.051+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=zip_csv_ingestion, task_id=extract_csv, run_id=scheduled__2025-02-11T00:00:00+00:00, execution_date=20250211T000000, start_date=20250212T221845, end_date=20250212T221846
[2025-02-12T22:18:46.103+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-12T22:18:46.104+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 11 for task extract_csv (File is not a zip file; 106)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/csv_to_gcs.py", line 25, in extract_csv
    with zipfile.ZipFile(LOCAL_ZIP_PATH, "r") as zip_ref:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/zipfile/__init__.py", line 1354, in __init__
    self._RealGetContents()
  File "/usr/local/lib/python3.12/zipfile/__init__.py", line 1421, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
[2025-02-12T22:18:46.158+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-12T22:18:46.186+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-12T22:18:46.190+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
