[2025-02-12T22:52:03.758+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-12T22:52:03.781+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: zip_csv_ingestion.download_zip manual__2025-02-12T22:52:00.084623+00:00 [queued]>
[2025-02-12T22:52:03.795+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: zip_csv_ingestion.download_zip manual__2025-02-12T22:52:00.084623+00:00 [queued]>
[2025-02-12T22:52:03.796+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-02-12T22:52:03.821+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): download_zip> on 2025-02-12 22:52:00.084623+00:00
[2025-02-12T22:52:03.833+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=95) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-12T22:52:03.835+0000] {standard_task_runner.py:72} INFO - Started process 97 to run task
[2025-02-12T22:52:03.839+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'zip_csv_ingestion', 'download_zip', 'manual__2025-02-12T22:52:00.084623+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/csv_to_gcs.py', '--cfg-path', '/tmp/tmpy59mqtn8']
[2025-02-12T22:52:03.841+0000] {standard_task_runner.py:105} INFO - Job 27: Subtask download_zip
[2025-02-12T22:52:03.916+0000] {task_command.py:467} INFO - Running <TaskInstance: zip_csv_ingestion.download_zip manual__2025-02-12T22:52:00.084623+00:00 [running]> on host d402094725ac
[2025-02-12T22:52:04.213+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='zip_csv_ingestion' AIRFLOW_CTX_TASK_ID='download_zip' AIRFLOW_CTX_EXECUTION_DATE='2025-02-12T22:52:00.084623+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-12T22:52:00.084623+00:00'
[2025-02-12T22:52:04.217+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-12T22:52:04.217+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-12T22:52:04.218+0000] {logging_mixin.py:190} INFO - Current task name:download_zip state:running start_date:2025-02-12 22:52:03.782391+00:00
[2025-02-12T22:52:04.218+0000] {logging_mixin.py:190} INFO - Dag name:zip_csv_ingestion and current dag run status:running
[2025-02-12T22:52:04.218+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-12T22:52:05.597+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/csv_to_gcs.py", line 31, in download_zip
    file_type = magic.from_file(LOCAL_ZIP_PATH, mime=True)
                ^^^^^
NameError: name 'magic' is not defined
[2025-02-12T22:52:05.620+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-02-12T22:52:05.620+0000] {logging_mixin.py:190} INFO - Task start:2025-02-12 22:52:03.782391+00:00 end:2025-02-12 22:52:05.619716+00:00 duration:1.837325
[2025-02-12T22:52:05.621+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): download_zip> dag:<DAG: zip_csv_ingestion> dagrun:<DagRun zip_csv_ingestion @ 2025-02-12 22:52:00.084623+00:00: manual__2025-02-12T22:52:00.084623+00:00, state:running, queued_at: 2025-02-12 22:52:00.096535+00:00. externally triggered: True>
[2025-02-12T22:52:05.621+0000] {logging_mixin.py:190} INFO - Failure caused by name 'magic' is not defined
[2025-02-12T22:52:05.621+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=zip_csv_ingestion, task_id=download_zip, run_id=manual__2025-02-12T22:52:00.084623+00:00, execution_date=20250212T225200, start_date=20250212T225203, end_date=20250212T225205
[2025-02-12T22:52:05.871+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-12T22:52:05.871+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 27 for task download_zip (name 'magic' is not defined; 97)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/csv_to_gcs.py", line 31, in download_zip
    file_type = magic.from_file(LOCAL_ZIP_PATH, mime=True)
                ^^^^^
NameError: name 'magic' is not defined
[2025-02-12T22:52:05.923+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-12T22:52:05.942+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-12T22:52:05.943+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
