[2025-02-15T17:19:26.533+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-15T17:19:26.578+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: zip_csv_ingestion.extract_csv scheduled__2025-02-13T00:00:00+00:00 [queued]>
[2025-02-15T17:19:26.624+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: zip_csv_ingestion.extract_csv scheduled__2025-02-13T00:00:00+00:00 [queued]>
[2025-02-15T17:19:26.625+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-02-15T17:19:26.734+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): extract_csv> on 2025-02-13 00:00:00+00:00
[2025-02-15T17:19:26.763+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=54) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-15T17:19:26.765+0000] {standard_task_runner.py:72} INFO - Started process 58 to run task
[2025-02-15T17:19:26.784+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'zip_csv_ingestion', 'extract_csv', 'scheduled__2025-02-13T00:00:00+00:00', '--job-id', '62', '--raw', '--subdir', 'DAGS_FOLDER/csv_to_gcs.py', '--cfg-path', '/tmp/tmpktg1dzu1']
[2025-02-15T17:19:26.785+0000] {standard_task_runner.py:105} INFO - Job 62: Subtask extract_csv
[2025-02-15T17:19:26.999+0000] {task_command.py:467} INFO - Running <TaskInstance: zip_csv_ingestion.extract_csv scheduled__2025-02-13T00:00:00+00:00 [running]> on host 4e731c556150
[2025-02-15T17:19:27.506+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='zip_csv_ingestion' AIRFLOW_CTX_TASK_ID='extract_csv' AIRFLOW_CTX_EXECUTION_DATE='2025-02-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-13T00:00:00+00:00'
[2025-02-15T17:19:27.507+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-15T17:19:27.511+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-15T17:19:27.512+0000] {logging_mixin.py:190} INFO - Current task name:extract_csv state:running start_date:2025-02-15 17:19:26.578918+00:00
[2025-02-15T17:19:27.512+0000] {logging_mixin.py:190} INFO - Dag name:zip_csv_ingestion and current dag run status:running
[2025-02-15T17:19:27.513+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-15T17:22:37.258+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
   